# ETL Project
---

## Extract

U.S. border-crossing data was extracted from the Bureau of Transportation Statistics (BTS) Border Crossing API (https://data.transportation.gov/Research-and-Statistics/Border-Crossing-Entry-Data/keg4-3bc2). Seeing as this data is found in the Socrata Public Data API, instead of extracting border-crossing data via JSON, the sodapy library was used.

In [44]:
# Dependencies
import pandas as pd
from sodapy import Socrata
import datetime as dt
from datetime import datetime

In [43]:
# Activate the Socrata Public Data API, specifically transportation data
client = Socrata("data.transportation.gov", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.transportation.gov,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [3]:
# Create conditions to ensure most rows will be used in final database
test_conditions = "date >= '2008-01-01' and value > 0 and (measure = 'Personal Vehicles' or \
                   measure = 'Personal Vehicles Passengers' or measure = 'Bus Passengers' or \
                   measure = 'Train Passengers') "

conditions = "date >= '2009-01-01' and value > 0"

In [7]:
# Request Border Entry data from specified API including additional conditions
results = client.get("keg4-3bc2", limit = 23000,  border = 'US-Canada Border', where = test_conditions)

In [8]:
# Create a Pandas Dataframe
results_df = pd.DataFrame.from_records(results)

In [45]:
# Preview the Dataframe
results_df = results_df.sort_values(by=['date'])

In [47]:
# Create a copy of the dataframe to manipulate the columns
clean_df = results_df.copy()
# Remove border and port code columns
clean_df = clean_df[['date','measure','port_name','state','value']]
# Change data type for date column
clean_df['date'] = pd.to_datetime(clean_df['date'])
# Set date as index
clean_df = clean_df.set_index('date')

In [48]:
clean_df

,measure,port_name,state,value
date,,,,
2008-01-01,Personal Vehicles,Oroville,Washington,14091
2008-01-01,Bus Passengers,Eastport,Idaho,227
2008-01-01,Personal Vehicles,Limestone,Maine,3030
2008-01-01,Bus Passengers,Calais,Maine,405
2008-01-01,Bus Passengers,Metaline Falls,Washington,183
2008-01-01,Personal Vehicles,Laurier,Washington,2870
2008-01-01,Personal Vehicles,Sarles,North Dakota,263
2008-01-01,Bus Passengers,Porthill,Idaho,457
2008-01-01,Bus Passengers,Laurier,Washington,134
2008-01-01,Personal Vehicles,Porthill,Idaho,9917
2008-01-01,Bus Passengers,Ogdensburg,New York,293
2008-01-01,Personal Vehicles,Beecher Falls,Vermont,4315
2008-01-01,Train Passengers,Detroit,Michigan,828
2008-01-01,Personal Vehicles,Northgate,North Dakota,1086
2008-01-01,Personal Vehicles,Hannah,North Dakota,167
2008-01-01,Bus Passengers,Frontier,Washington,526
2008-01-01,Personal Vehicles,Opheim,Montana,263
2008-01-01,Personal Vehicles,Roosville,Montana,5094
2008-01-01,Personal Vehicles,Highgate Springs-Alburg,Vermont,29939
2008-01-01,Personal Vehicles,Blaine,Washington,193559
2008-01-01,Personal Vehicles,Dunseith,North Dakota,3225
2008-01-01,Personal Vehicles,Carbury,North Dakota,796
2008-01-01,Bus Passengers,Anacortes,Washington,17
2008-01-01,Personal Vehicles,Alcan,Alaska,749
2008-01-01,Personal Vehicles,Del Bonita,Montana,978
2008-01-01,Personal Vehicles,Champlain-Rouses Point,New York,58683
2008-01-01,Bus Passengers,Pembina,North Dakota,3275
2008-01-01,Personal Vehicles,Warroad,Minnesota,7383
2008-01-01,Personal Vehicles,Grand Portage,Minnesota,14470
2008-01-01,Train Passengers,Baudette,Minnesota,224
...,...,...,...,...
2019-06-01,Personal Vehicles,International Falls-Ranier,Minnesota,41703
2019-06-01,Bus Passengers,International Falls-Ranier,Minnesota,792
2019-06-01,Personal Vehicles,Grand Portage,Minnesota,22204
2019-06-01,Bus Passengers,Grand Portage,Minnesota,772
2019-06-01,Personal Vehicles,Baudette,Minnesota,16330
2019-06-01,Bus Passengers,Baudette,Minnesota,378
2019-06-01,Train Passengers,Sault Sainte Marie,Michigan,58
2019-06-01,Personal Vehicles,Opheim,Montana,371
2019-06-01,Bus Passengers,Sault Sainte Marie,Michigan,1124
2019-06-01,Bus Passengers,Piegan,Montana,579
2019-06-01,Bus Passengers,Raymond,Montana,36
2019-06-01,Personal Vehicles,Derby Line,Vermont,49419
2019-06-01,Personal Vehicles,Beecher Falls,Vermont,7482
2019-06-01,Personal Vehicles,Antler,North Dakota,574
2019-06-01,Personal Vehicles,Ambrose,North Dakota,105
2019-06-01,Personal Vehicles,Willow Creek,Montana,215
2019-06-01,Personal Vehicles,Wildhorse,Montana,1462
2019-06-01,Bus Passengers,Wildhorse,Montana,50
2019-06-01,Personal Vehicles,Whitlash,Montana,36
2019-06-01,Personal Vehicles,Turner,Montana,760
2019-06-01,Bus Passengers,Turner,Montana,25
2019-06-01,Train Passengers,Sweetgrass,Montana,195
2019-06-01,Personal Vehicles,Sweetgrass,Montana,16154
2019-06-01,Bus Passengers,Sweetgrass,Montana,337
2019-06-01,Personal Vehicles,Scobey,Montana,544
2019-06-01,Personal Vehicles,Roosville,Montana,16818
2019-06-01,Bus Passengers,Roosville,Montana,195
2019-06-01,Personal Vehicles,Raymond,Montana,2431
2019-06-01,Personal Vehicles,Piegan,Montana,13899
2019-06-01,Bus Passengers,Alcan,Alaska,1047

In [36]:
clean_df

,date,measure,port_name,state,value
0,2008-01-01,Personal Vehicles,Oroville,Washington,14091
1,2008-01-01,Personal Vehicles,Nighthawk,Washington,323
2,2008-01-01,Personal Vehicles,Turner,Montana,221
3,2008-01-01,Bus Passengers,Champlain-Rouses Point,New York,14691
4,2008-01-01,Bus Passengers,Sault Sainte Marie,Michigan,20912
5,2008-01-01,Personal Vehicles,Ambrose,North Dakota,93
6,2008-01-01,Bus Passengers,Massena,New York,2473
7,2008-01-01,Train Passengers,Vanceboro,Maine,55
8,2008-01-01,Train Passengers,Eastport,Idaho,172
9,2008-01-01,Bus Passengers,Sweetgrass,Montana,184
10,2008-01-01,Bus Passengers,Derby Line,Vermont,3904
11,2008-01-01,Train Passengers,Portal,North Dakota,627
12,2008-01-01,Bus Passengers,Dalton Cache,Alaska,95
13,2008-01-01,Train Passengers,Blaine,Washington,2014
14,2008-01-01,Train Passengers,International Falls-Ranier,Minnesota,674
15,2008-01-01,Personal Vehicles,Dalton Cache,Alaska,448
16,2008-01-01,Personal Vehicles,Lancaster,Minnesota,3401
17,2008-01-01,Bus Passengers,Alcan,Alaska,22
18,2008-01-01,Personal Vehicles,Fort Fairfield,Maine,12449
19,2008-01-01,Bus Passengers,Detroit,Michigan,83524
20,2008-01-01,Bus Passengers,Point Roberts,Washington,1487
21,2008-01-01,Bus Passengers,Houlton,Maine,198
22,2008-01-01,Personal Vehicles,Lynden,Washington,38796
23,2008-01-01,Bus Passengers,Roosville,Montana,547
24,2008-01-01,Bus Passengers,Eastport,Maine,70
25,2008-01-01,Personal Vehicles,Ferry,Washington,541
26,2008-01-01,Train Passengers,Calais,Maine,22
27,2008-01-01,Personal Vehicles,Norton,Vermont,5475
28,2008-01-01,Personal Vehicles,Morgan,Montana,319
29,2008-01-01,Train Passengers,Pembina,North Dakota,224
...,...,...,...,...,...
21424,2019-06-01,Personal Vehicles,Sherwood,North Dakota,1303
21425,2019-06-01,Personal Vehicles,Sarles,North Dakota,325
21426,2019-06-01,Bus Passengers,Sarles,North Dakota,28
21427,2019-06-01,Train Passengers,Portal,North Dakota,444
21428,2019-06-01,Personal Vehicles,Portal,North Dakota,6947
21429,2019-06-01,Bus Passengers,Portal,North Dakota,244
21430,2019-06-01,Train Passengers,Pembina,North Dakota,248
21431,2019-06-01,Personal Vehicles,Pembina,North Dakota,24210
21432,2019-06-01,Bus Passengers,Pembina,North Dakota,1268
21433,2019-06-01,Train Passengers,Northgate,North Dakota,45
21434,2019-06-01,Personal Vehicles,Northgate,North Dakota,1122
21435,2019-06-01,Personal Vehicles,Noonan,North Dakota,2320
21436,2019-06-01,Personal Vehicles,Neche,North Dakota,3489
21437,2019-06-01,Personal Vehicles,Maida,North Dakota,725
21438,2019-06-01,Personal Vehicles,Hansboro,North Dakota,518
21439,2019-06-01,Personal Vehicles,Hannah,North Dakota,84
21440,2019-06-01,Personal Vehicles,Fortuna,North Dakota,1434
21441,2019-06-01,Personal Vehicles,Dunseith,North Dakota,6161
21442,2019-06-01,Bus Passengers,Dunseith,North Dakota,220
21443,2019-06-01,Personal Vehicles,Carbury,North Dakota,998
21444,2019-06-01,Bus Passengers,Carbury,North Dakota,30
21445,2019-06-01,Train Passengers,Skagway,Alaska,27454
21446,2019-06-01,Personal Vehicles,Skagway,Alaska,10886
21447,2019-06-01,Bus Passengers,Skagway,Alaska,48767
21448,2019-06-01,Personal Vehicles,Ketchikan,Alaska,458
21449,2019-06-01,Bus Passengers,Ketchikan,Alaska,60
21450,2019-06-01,Personal Vehicles,Dalton Cache,Alaska,2755
21451,2019-06-01,Bus Passengers,Dalton Cache,Alaska,156
21452,2019-06-01,Personal Vehicles,Alcan,Alaska,10850
21453,2019-06-01,Bus Passengers,Alcan,Alaska,1047

In [10]:
results_df['measure'].value_counts()

Personal Vehicles    11568
Bus Passengers        6542
Train Passengers      3344
Name: measure, dtype: int64